### ISSUE TITLE
Uncaught SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by jasonleewilson** [nyg/bitstamp-ticker#1]
First off, awesome work.  I really like your simple approach.  Thank you for sharing.

I am getting this console error:
"Uncaught SyntaxError: Unexpected token u"

Noticed the same error is showing in your demo.  I know this is an old project, but would be super cool to resurrect the project.

Thank you in advance, and look forward to hearing your input.

**Comment by nyg** [comment]
Hi, thanks for your comment!
I have fixed the issue, the demo works again now.
It appears YQL stopped accepting "?" as the callback value and therefore the returned JSON was not as expected...

**Comment by jasonleewilson** [comment]
Awesome!!! Thank you for looking into it for me.  Again great work!!!
