### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by ahmetkakacak** [nyg/bitstamp-ticker#2]
Hi @nyg,

What is the software license for this repository? If there isn't a specific license, what are the terms to copy, modify and distribute the code?

Thanks in advance,
ahmedus

**Comment by nyg** [comment]
Hi, I've added the license file at the root of the repo. It's a BSD-type license.

**Comment by ahmetkakacak** [comment]
Thanks for your response on that. I'll also distribute my fork with the same license.
